<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="EXO-BLR-LT214" failures="1" tests="1" name="renameChannel" time="0.726" errors="0" timestamp="11 May 2020 09:34:31 GMT">
  <testcase classname="com.plivo.test.ApiTest" name="renameChannel" time="0.714">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.plivo.test.ApiTest.responseToPojoAndValidate(ApiTest.java:39)
	at com.plivo.test.ApiTest.renameChannel(ApiTest.java:81)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- renameChannel -->
  <testcase classname="com.plivo.test.ApiTest" name="listAllChannels" time="0.0">
    <ignored/>
  </testcase> <!-- listAllChannels -->
  <testcase classname="com.plivo.test.ApiTest" name="validateChannelArchive" time="0.0">
    <ignored/>
  </testcase> <!-- validateChannelArchive -->
  <testcase classname="com.plivo.test.ApiTest" name="joinChannel" time="0.0">
    <ignored/>
  </testcase> <!-- joinChannel -->
  <testcase classname="com.plivo.test.ApiTest" name="createChannel" time="0.0">
    <ignored/>
  </testcase> <!-- createChannel -->
  <testcase classname="com.plivo.test.ApiTest" name="archiveChannel" time="0.0">
    <ignored/>
  </testcase> <!-- archiveChannel -->
</testsuite> <!-- renameChannel -->
